from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable

from deck_builder.design_token_validator import DesignTokenValidator


@dataclass(frozen=True)
class TokenAutogenerationRules:
    max_variants_per_token: int = 2
    numeric_scale_down: float = 0.875
    numeric_scale_up: float = 1.125
    allowed_namespaces: tuple[str, ...] = (
        "color",
        "typography",
        "spacing",
        "layout",
        "chart",
        "brand",
        "component",
    )


@dataclass(frozen=True)
class TokenAutogenerationResult:
    tokens: tuple[dict[str, Any], ...]
    rejected: tuple[str, ...]


class DesignTokenAutogenerator:
    """Generate bounded deterministic token variants from schema-valid seed tokens."""

    def __init__(
        self,
        validator: DesignTokenValidator | None = None,
        rules: TokenAutogenerationRules | None = None,
    ) -> None:
        self.validator = validator or DesignTokenValidator.from_file()
        self.rules = rules or TokenAutogenerationRules()

    def generate(self, seed_tokens: Iterable[dict[str, Any]]) -> TokenAutogenerationResult:
        generated: list[dict[str, Any]] = []
        rejected: list[str] = []

        for token in sorted(seed_tokens, key=lambda item: item.get("name", "")):
            result = self.validator.validate(token)
            if not result.valid:
                rejected.append(f"{token.get('name', '<unnamed>')}: {'; '.join(result.errors)}")
                continue
            if token["namespace"] not in self.rules.allowed_namespaces:
                rejected.append(f"{token['name']}: namespace not allowed")
                continue

            try:
                variants = self._variants(token)
            except ValueError as exc:
                rejected.append(f"{token['name']}: {exc}")
                continue
            accepted_for_seed = 0
            for variant in variants:
                if accepted_for_seed >= self.rules.max_variants_per_token:
                    break
                validation = self.validator.validate(variant)
                if validation.valid:
                    generated.append(variant)
                    accepted_for_seed += 1
                else:
                    rejected.append(f"{variant.get('name', '<unnamed>')}: {'; '.join(validation.errors)}")

        return TokenAutogenerationResult(tokens=tuple(generated), rejected=tuple(rejected))

    def _variants(self, token: dict[str, Any]) -> tuple[dict[str, Any], ...]:
        if token["type"] == "color" and isinstance(token["value"], str):
            return (
                self._color_variant(token, "tint", 24),
                self._color_variant(token, "shade", -24),
            )
        if token["type"] in {"spacing", "font_size", "dimension", "radius", "number"}:
            return (
                self._numeric_variant(token, "compact", self.rules.numeric_scale_down),
                self._numeric_variant(token, "spacious", self.rules.numeric_scale_up),
            )
        if token["type"] == "font_family":
            return (self._string_variant(token, "fallback", f"{token['value']}, Arial, sans-serif"),)
        return ()

    @staticmethod
    def _base_variant(token: dict[str, Any], suffix: str, value: Any) -> dict[str, Any]:
        return {
            "namespace": token["namespace"],
            "name": f"{token['name']}.{suffix}",
            "type": token["type"],
            "value": value,
            "unit": token.get("unit"),
            "source": "generated",
            "description": f"Autogenerated {suffix} variant for {token['name']}.",
        }

    @classmethod
    def _numeric_variant(cls, token: dict[str, Any], suffix: str, multiplier: float) -> dict[str, Any]:
        value = token["value"]
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return cls._base_variant(token, suffix, value)
        scaled = value * multiplier
        if isinstance(value, int):
            scaled = max(1, round(scaled))
        else:
            scaled = round(scaled, 4)
        return cls._base_variant(token, suffix, scaled)

    @classmethod
    def _string_variant(cls, token: dict[str, Any], suffix: str, value: str) -> dict[str, Any]:
        return cls._base_variant(token, suffix, value)

    @classmethod
    def _color_variant(cls, token: dict[str, Any], suffix: str, delta: int) -> dict[str, Any]:
        red, green, blue = cls._parse_hex(token["value"])
        value = f"#{cls._clamp(red + delta):02X}{cls._clamp(green + delta):02X}{cls._clamp(blue + delta):02X}"
        return cls._base_variant(token, suffix, value)

    @staticmethod
    def _parse_hex(value: str) -> tuple[int, int, int]:
        candidate = value.strip()
        if candidate.startswith("#"):
            candidate = candidate[1:]
        if len(candidate) == 3:
            candidate = "".join(char * 2 for char in candidate)
        if len(candidate) != 6:
            raise ValueError(f"Invalid hex color: {value}")
        return int(candidate[0:2], 16), int(candidate[2:4], 16), int(candidate[4:6], 16)

    @staticmethod
    def _clamp(value: int) -> int:
        return min(255, max(0, value))
